# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_INTEL_SOCFPGA) += socfpga_agilex_n6000.dtb \
				socfpga_agilex_socdk.dtb \
				socfpga_agilex_socdk_atfboot.dtb \
				socfpga_agilex_socdk_qspi_atfboot.dtb \
				socfpga_agilex_socdk_sdmmc_atfboot.dtb \
				socfpga_agilex_socdk_nand.dtb \
				socfpga_agilex_socdk_emmc.dtb \
				socfpga_agilex3_socdk.dtb \
				socfpga_agilex3_socdk_qspi_atfboot.dtb \
				socfpga_agilex3_socdk_sdmmc_atfboot.dtb \
				socfpga_agilex5_de25_nano.dtb \
				socfpga_agilex5_socdk_a0.dtb \
				socfpga_agilex5_socdk_a0_emmc.dtb \
				socfpga_agilex5_socdk_a0_modular.dtb \
				socfpga_agilex5_socdk.dtb \
				socfpga_agilex5_socdk_013b.dtb \
				socfpga_agilex5_socdk_013b_qspi_atfboot.dtb \
				socfpga_agilex5_socdk_013b_sdmmc_atfboot.dtb \
				socfpga_agilex5_socdk_debug.dtb \
				socfpga_agilex5_socdk_emmc.dtb \
				socfpga_agilex5_socdk_emmc_atfboot.dtb \
				socfpga_agilex5_socdk_nand_a0.dtb \
				socfpga_agilex5_socdk_nand.dtb \
				socfpga_agilex5_socdk_nand_atfboot.dtb \
				socfpga_agilex5_socdk_qspi_atfboot.dtb \
				socfpga_agilex5_socdk_sdmmc_atfboot.dtb \
				socfpga_agilex5_socdk_tsn_cfg2_a0.dtb \
				socfpga_agilex5_socdk_tsn_cfg2.dtb \
				socfpga_agilex5_socdk_modular.dtb \
				socfpga_agilex7m_socdk.dtb \
				socfpga_agilex7f_socdk_pcie_root_port.dtb \
				socfpga_agilex7i_socdk_pcie_root_port.dtb \
				socfpga_agilex7m_socdk_pcie_root_port.dtb \
				socfpga_agilex7f_socdk_multiqspi.dtb \
				socfpga_n5x_socdk.dtb
dtb-$(CONFIG_ARCH_KEEMBAY) += keembay-evm.dtb
dtb-$(CONFIG_ARCH_DM) += socfpga_dm_simics.dtb
