# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_INTEL_SOCFPGA) += socfpga_n6000_10G_ptp.dtb \
				socfpga_agilex5_eth_1p10g.dtb \
				socfpga_n6000_10G_rel3_ptp.dtb \
				socfpga_n6000_25G_ptp.dtb \
				socfpga_n6000_25G_rel3_ptp.dtb \
				socfpga_fm87_ftile_10g.dtb \
				socfpga_agilex_n6000.dtb \
				socfpga_agilex_socdk.dtb \
				socfpga_agilex_socdk_atfboot.dtb \
				socfpga_fm87_ftile_10g_1port.dtb \
				socfpga_fm87_ftile_25g_ptp.dtb \
				socfpga_fm87_ftile_10g_2port_ptp.dtb \
				socfpga_fm87_ftile_25g_2port_ptp.dtb \
				socfpga_fm87_ftile_25g_2port_mcq_ptp.dtb \
				socfpga_fm87_ftile_25g_1port_mcq_ptp.dtb \
				socfpga_agilex_socdk_nand.dtb \
				socfpga_agilex3_socdk.dtb \
				socfpga_agilex5_socdk.dtb \
				socfpga_agilex_n6010.dtb \
				socfpga_agilex5_socdk.dtb \
				socfpga_agilex5_socdk_b0.dtb \
				socfpga_agilex5_socdk_debug.dtb \
				socfpga_agilex5_socdk_emmc.dtb \
				socfpga_agilex5_socdk_nand.dtb \
				socfpga_agilex5_socdk_nand_b0.dtb \
				socfpga_agilex5_socdk_nand_b0_atfboot.dtb \
				socfpga_agilex5_socdk_swvp_b0.dtb \
				socfpga_agilex5_socdk_tsn_cfg2.dtb \
				socfpga_agilex5_socdk_tsn_cfg2_b0.dtb \
				socfpga_agilex5_socdk_modular.dtb \
				socfpga_agilex7m_socdk.dtb \
				socfpga_agilex7f_socdk_pcie_root_port.dtb \
				socfpga_agilex7i_socdk_pcie_root_port.dtb \
				socfpga_agilex7m_socdk_pcie_root_port.dtb \
				socfpga_agilex7f_socdk_multiqspi.dtb \
				socfpga_n5x_socdk.dtb
dtb-$(CONFIG_ARCH_KEEMBAY) += keembay-evm.dtb
dtb-$(CONFIG_ARCH_DM) += socfpga_dm_simics.dtb
