name: "Setup Resource Version"
description: "define the resource versions to be used across the CI Pipelines"
outputs:
  SOCFPGA_REFDES_VERSION:
    description: "GSRD/GHRD resource used for regtest"
    value: ${{ steps.set-version.outputs.SOCFPGA_REFDES_VERSION }}
  QPDS_VERSION_agilex5:
    description: "agilex5 QPDS version to run tests with"
    value: ${{ steps.set-version.outputs.QPDS_VERSION_agilex5 }}
  GHRD_VERSION_agilex5:
    description: "agilex5 GHRD version to run tests with"
    value: ${{ steps.set-version.outputs.GHRD_VERSION_agilex5 }}
runs:
  using: "composite"
  steps:
  - id: set-version
    shell: bash
    run: |
      echo "SOCFPGA_REFDES_VERSION=25.3.1/668" >> $GITHUB_OUTPUT
      echo "QPDS_VERSION_agilex5=26.1.1/15" >> $GITHUB_OUTPUT
      echo "GHRD_VERSION_agilex5=main/3284" >> $GITHUB_OUTPUT
