name: Reusable Coverity flow

on:
  workflow_call:
    secrets:
      GIT_USER:
        required: true
      GIT_TOKEN:
        required: true
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string

env:
  WORKFLOW_REPO_REF: cicd-2026.03

jobs:
  ci-coverity-build:
    runs-on: [ arc, lapwing, workspace_type=tmp-workspace, coverity/2024.3.0, gcc/9.3.0, python/3.12.10 ]
    env:
      # Disable the warnings of Security violation. We need to check why this is trigger later, plaintext password.
      EC_DISABLE_VAL: project,system

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Workflow Script checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.WORKFLOW_REPO_REF }}
          repository: altera-innersource/applications.devops.build-bot.github-pr-workflow
          path: workflow_scripts
          token: ${{ secrets.GIT_TOKEN }}

      #we are interested in steps.run-options.outputs.full_coverity, but since uboot build everything this is not used ATM
      - name: Get CI Run Options
        id: run-options
        uses: ./.github/actions/ci-run-options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          script_dir: workflow_scripts

      - name: Run Coverity Build (PR flow)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          export TMP_ROOT=$RUNNER_TEMP
          python3 workflow_scripts/workflow_Coverity_Build.py ${{ github.workspace }} -c linux ${{ inputs.head_ref }} ${{ inputs.base_ref }} \
            --github-token ${{ secrets.GIT_TOKEN }} --github-pr ${{ github.event.pull_request.number }}

      - name: Run Coverity Build (non-PR flow)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          export TMP_ROOT=$RUNNER_TEMP
          python3 workflow_scripts/workflow_Coverity_Build.py ${{ github.workspace }} -c linux ${{ inputs.head_ref }} ${{ inputs.base_ref }}

      - name: linux-coverity-result-json
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverity-result-json
          path: ${{ github.workspace }}/coverity_results.tar.gz
          retention-days: 1

  ci-coverity-parse-result:
    needs: ci-coverity-build
    runs-on: [ arc, lapwing, workspace_type=tmp-workspace, python/3.12.10 ]

    steps:

      - name: Workflow Script checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.WORKFLOW_REPO_REF }}
          repository: altera-innersource/applications.devops.build-bot.github-pr-workflow
          path: workflow_scripts
          token: ${{ secrets.GIT_TOKEN }}

      - name: Download coverity result
        uses: actions/download-artifact@v4
        with:
          name: linux-coverity-result-json

      - name: Extract coverity result
        run: |
          tar -xzf coverity_results.tar.gz
          ls -al *.json

      - name : Run Coverity Parser
        run: |
          python3 workflow_scripts/workflow_Coverity_Check_Result.py --github-repo ${{ github.repository }} -p ${{ github.event.pull_request.number || 0 }} \
            --github-token ${{ secrets.GITHUB_TOKEN }} linux_output_defect_prechange.json linux_output_defect_postchange.json -o linux_output_defect.csv

      - name: linux-coverity-report
        # Run Coverity Parser may fail if it detects new defects, but we always need to upload the report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverity-report
          path: ${{ github.workspace }}/linux_output_defect.csv
          retention-days: 14
