name: Reusable Coverity flow

on:
  workflow_call:
    secrets:
      GIT_USER:
        required: true
      GIT_TOKEN:
        required: true
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string

env:
  WORKFLOW_REPO_REF: cicd-2025.12

jobs:
  ci-coverity-build:
    runs-on: [ arc, lapwing, workspace_type=tmp-workspace, coverity/2024.3.0, gcc/9.3.0, python/3.12.10 ]
    env:
      # Disable the warnings of Security violation. We need to check why this is trigger later, plaintext password.
      EC_DISABLE_VAL: project,system

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Workflow Script checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.WORKFLOW_REPO_REF }}
          repository: altera-innersource/applications.devops.build-bot.github-pr-workflow
          path: workflow_scripts
          token: ${{ secrets.GIT_TOKEN }}

      - name: Run Coverity Build
        id: coverity-build
        run: |
          export WORK_DIR=$RUNNER_TEMP
          python3 workflow_scripts/workflow_Coverity_Build.py ${{ github.workspace }} --software-component linux ${{ inputs.head_ref }} ${{ inputs.base_ref }}

      - name: linux-coverity-report-prechange
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverity-report-prechange
          path: linux_output_defect_prechange.json
          retention-days: 1

      - name: linux-coverity-report-postchange
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverity-report-postchange
          path: linux_output_defect_postchange.json
          retention-days: 1

  ci-coverity-parse-result:
    needs: ci-coverity-build
    runs-on: [ arc, lapwing, workspace_type=tmp-workspace, python/3.12.10 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Workflow Script checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.WORKFLOW_REPO_REF }}
          repository: altera-innersource/applications.devops.build-bot.github-pr-workflow
          path: workflow_scripts
          token: ${{ secrets.GIT_TOKEN }}

      - name: Download coverity result prechange
        uses: actions/download-artifact@v4
        with:
          name: linux-coverity-report-prechange

      - name: Download coverity result postchange
        uses: actions/download-artifact@v4
        with:
          name: linux-coverity-report-postchange

      - name : Run Coverity Parser
        run: |
          export PYTHONUSERBASE=$RUNNER_TEMP/.local
          mkdir -p $PYTHONUSERBASE
          bash workflow_scripts/workflow_Coverity_Parser.sh ${{ github.workspace }} ${{ github.event.repository.name }} ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }}

      - name: linux-coverity-report
        uses: actions/upload-artifact@v4
        with:
          name: linux-coverity-report
          path: linux_output_defect.csv
          retention-days: 14
