name: altera-linux-ci-pipeline
###############################################################################
# Altera SOCFPGA linux Build Pipeline
###############################################################################

on:
  pull_request:
     branches: [ "socfpga-*", "cicd-*" ]
     types: [opened, synchronize, reopened, review_requested, review_submission]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  WORKFLOW_REPO_REF: cicd-2025.12
  TMP_DIR_ROOT: /p/psg/swip/etools/esv/gh_build_temp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-cleanup-workspace:
    runs-on: [lapwing, arc, workspace_type=tmp-workspace, mem=8000, git, _site=png]
    steps:
      - name: delete workspace older than 1 day
        run: |
          find $TMP_DIR_ROOT -maxdepth 1 -name *-linux-* -type d -mtime +1 -user $USER
          find $TMP_DIR_ROOT -maxdepth 1 -name *-linux-* -type d -mtime +1 -user $USER -exec rm -rf {} +

#This action extracts the new commits and performs checkpatch checks on it.
  ci-checkpatch:
    if: ${{ github.event_name == 'pull_request' }}
    continue-on-error: ${{  !startswith(github.base_ref, 'socfpga-')  }}
    runs-on: [lapwing, arc, workspace_type=tmp-workspace, git]
    # Check patch only can run at pull request as it is hard to determine the commit during the push event.
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This will pull the whole repo, otherwise cannot compare commit.
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Workflow Script checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.WORKFLOW_REPO_REF }}
          repository: altera-innersource/applications.devops.build-bot.github-pr-workflow
          path: workflow_scripts
          token: ${{ secrets.GIT_TOKEN }}

      - name: Checkpatch.pl
        run: |
          bash workflow_scripts/workflow_Checkpatch.sh ${{ github.workspace }} ${{ github.event.repository.name }} ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }} ${{ github.head_ref }} ${{ github.base_ref }}

  ci-resource-version:
    runs-on:  [ altera-innersource.prod.amr.quartus ]
    outputs:
      SOCFPGA_REFDES_VERSION: ${{ steps.set-version.outputs.SOCFPGA_REFDES_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - id: set-version
        uses: ./.github/actions/ci-resource-version


#This action performs a build test using an ubuntu container.
  ci-build:
    uses: ./.github/workflows/ci-build.yml
    secrets:
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

  ci-test-select:
    uses: ./.github/workflows/ci-test-select.yml
    secrets:
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AGPT_TOKEN: ${{ secrets.AGPT_TOKEN }}
    with:
      #for pull request, use head/base ref, for push/workflow run, use head of branch with default branch as base
      head_ref: ${{ (github.event_name == 'pull_request' && github.head_ref)
                || github.ref_name }}
      base_ref: ${{ (github.event_name == 'pull_request' && github.base_ref)
                || github.event.repository.default_branch }}

#This action runs regression test
  ci-verification:
    needs: [ci-resource-version, ci-build, ci-test-select]
    uses: ./.github/workflows/ci-verify.yml
    secrets:
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      socfpga_refdes_version: ${{ needs.ci-resource-version.outputs.SOCFPGA_REFDES_VERSION }}

  ci-coverity:
    uses: ./.github/workflows/ci-coverity.yml
    secrets:
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      #for pull request, use head/base ref, for push/workflow run, use head of branch with default branch as base
      head_ref: ${{ (github.event_name == 'pull_request' && github.head_ref)
                || github.ref_name }}
      base_ref: ${{ (github.event_name == 'pull_request' && github.base_ref)
                || github.event.repository.default_branch }}

#This action checks if the branch has been released and if so block PR until approved by repo Admin
  ci-check-tag:
    runs-on: [self-hosted,pg-embedded-runner]
    container:
      image: amr-registry.sc.altera.com/pse-pswe-software-ba/embedded_coverity:ubuntu20.04.0_6-new-proxy-inbuilt
      options: -v /mnt/nfs_share/site/proj/psg:/p/psg
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    steps:
      - uses: actions/checkout@v4
      - name : Download check_tag script
        run: |
          git config --global credential.helper store
          git clone https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/altera-innersource/applications.devops.build-bot.github-pr-workflow
          cd applications.devops.build-bot.github-pr-workflow
          git checkout master

      - name: Check_Tag
        run: |
          cd applications.devops.build-bot.github-pr-workflow
          bash workflow_Check_Tag.sh ${{ github.workspace }} ${{ github.event.repository.name }} ${{ github.event.pull_request.number }} ${{ github.base_ref }} ${{ secrets.GITHUB_TOKEN }}

  #This is the commit gate that ensures all required checks are passing before the PR is allowed to be merged.
  ci-check-pr-status:
    runs-on: [ arc, lapwing, workspace_type=tmp-workspace ]
    needs: [ci-checkpatch, ci-build, ci-verification, ci-check-tag, ci-coverity]
    #always runs even if ci-checkpatch is skipped when running PR not from socfpga_v*
    if: always()
    steps:
     - name: On failure
       if: ${{ needs.ci-checkpatch.result == 'failure'
            || needs.ci-build.result != 'success'
            || needs.ci-verification.result != 'success'
            || needs.ci-check-tag.result != 'success'
            || needs.ci-coverity.result != 'success' }}
       run: |
          echo "Status check has failed."
          exit 1
