name: Reusable CI Multistage Testrun Flow For CI

on:
  workflow_call:
    secrets:
      GIT_USER:
        required: true
      GIT_TOKEN:
        required: true
    inputs:
      test_matrix:
        description: 'JSON string with [[stage1 test_configs], [stage2 test_configs]]'
        required: true
        type: string
    outputs:
      arc_job_ids:
        description: "JSON array of the top level ARC job when running reg_exe for each test in each stage"
        value: ${{ jobs.ci-testrun-multistage-status.outputs.arc_job_ids }}

jobs:
  ci-testrun-stage1:
    if: ${{ join(fromJSON(inputs.test_matrix)[0]) != '' }}
    uses: ./.github/workflows/ci-testrun.yml
    secrets:
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      test_matrix: ${{ toJSON(fromJSON(inputs.test_matrix)[0]) }}

  ci-testrun-stage2:
    if: ${{ join(fromJSON(inputs.test_matrix)[1]) != '' }}
    needs: [ci-testrun-stage1]
    uses: ./.github/workflows/ci-testrun.yml
    secrets:
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      test_matrix: ${{ toJSON(fromJSON(inputs.test_matrix)[1]) }}

  ci-testrun-multistage-status:
    needs: [ci-testrun-stage1, ci-testrun-stage2]
    runs-on: [lapwing, arc, workspace_type=tmp-workspace]
    if: always()
    outputs:
        arc_job_ids: ${{ steps.collect-arc-job-id.outputs.arc_job_ids }}
    steps:
      - name: Collect ARB job IDs
        id: collect-arc-job-id
        #ci-testrun will produce arc_job_ids output regardless of pass or fail
        run: |
          echo '${{ needs.ci-testrun-stage1.outputs.arc_job_ids }}' >> stage1_result.json
          echo '${{ needs.ci-testrun-stage2.outputs.arc_job_ids }}' >> stage2_result.json
          arc_job_ids=$(jq -c -s 'add' stage1_result.json stage2_result.json)
          echo "arc_job_ids=$arc_job_ids"
          echo "arc_job_ids=$arc_job_ids" >> $GITHUB_OUTPUT

      - name: On failure
        if: ${{ needs.ci-testrun-stage1.result == 'failure'
             || needs.ci-testrun-stage2.result == 'failure' }}
        run: |
          echo "One of the test stage has failed."
          exit 1
